=== 001466/codegen/build/codegen.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="codegen" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="charset" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="UTF-8" />
							<xs:enumeration value="GBK" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<!--连接 -->

				<xs:element name="database" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:attributeGroup ref="database"></xs:attributeGroup>
					</xs:complexType>
				</xs:element>
				<!--变量 -->
				<xs:element name="variables" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="variable" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attributeGroup ref="variableAttr"></xs:attributeGroup>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<!--模板 -->
				<xs:element name="templates" maxOccurs="1" minOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="template">
								<xs:complexType>
									<xs:attributeGroup ref="templateAttr"></xs:attributeGroup>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="basepath" type="xs:string">
							<xs:annotation>
								<xs:documentation>模板的基路径.</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<!-- 生成文件模版 -->
				<xs:element name="files" maxOccurs="1" minOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="file">
								<xs:complexType>
									<xs:attributeGroup ref="fileAttr"></xs:attributeGroup>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="baseDir" type="xs:string">
							<xs:annotation>
								<xs:documentation>生成文件的基路径.</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				
				<!--表变量 -->
				<xs:element name="table" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded" minOccurs="1">
							<!--表级别变量 -->
							<xs:element name="variable" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attributeGroup ref="variableAttr"></xs:attributeGroup>
								</xs:complexType>
							</xs:element>
							<xs:element name="subtable" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>子表</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attributeGroup ref="tableAttr"></xs:attributeGroup>
								</xs:complexType>
								
							</xs:element>
							
						</xs:sequence>
						<xs:attribute name="tableName" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>数据库表名.</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						
					</xs:complexType>
				</xs:element>
				<xs:element name="genAll" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded" minOccurs="1">
							<xs:element name="file">
								<xs:annotation>
									<xs:documentation>需要生成的文件</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="variable" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attributeGroup ref="variableAttr"></xs:attributeGroup>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attributeGroup ref="batFleAttr"></xs:attributeGroup>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="tableNames" type="xs:string" use="optional">
							<xs:annotation>
								<xs:documentation>数据库表名,使用逗号分割.</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>



	<!--连接属性 -->
	<xs:attributeGroup name="database">
		<xs:attribute name="dbHelperClass" use="required">
			<xs:annotation>
				<xs:documentation>
					dbHelper实现类
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="url" use="required">
			<xs:annotation>
				<xs:documentation>
					数据库URL
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="username" use="required">
			<xs:annotation>
				<xs:documentation>
					用户名
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="password" use="required">
			<xs:annotation>
				<xs:documentation>
					密码
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
	<!--模板属性 -->
	<xs:attributeGroup name="templateAttr">

		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					模版ID
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute name="path" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					模板路径
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
	<!--变量属性 -->
	<xs:attributeGroup name="variableAttr">
		<xs:attribute name="name" use="required" type="xs:string">
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="required"></xs:attribute>
	</xs:attributeGroup>
	<!--文件属性-->
	<xs:attributeGroup name="fileAttr">
		<xs:attribute name="refTemplate" type="xs:string" use="required" >
			<xs:annotation>
				<xs:documentation>
					引用的模板,引用模板的ID
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="filename" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					生成的文件名称.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="dir" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					生成的文件存放的目录.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	
		<xs:attribute name="append" type="xs:boolean" use="optional" default="false">
			<xs:annotation>
					<xs:documentation>是否添加</xs:documentation>
			</xs:annotation>
			
		</xs:attribute>
		<xs:attribute name="insertTag" default="&lt;!--insertbefore--&gt;" use="optional">
			<xs:annotation>
					<xs:documentation>插入标签:功能在标签之前插入新的内容</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="startTag" default="start{tabname}" use="optional">
			<xs:annotation>
				<xs:documentation>起始标签</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="endTag" default="end{tabname}" use="optional">
			<xs:annotation>
				<xs:documentation>结束标签</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
	
	<xs:attributeGroup name="tableAttr">
		<xs:attribute name="tablename" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					表名
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="foreignKey" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					外键
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>

	<xs:attributeGroup name="batFleAttr">
		<xs:attribute name="refTemplate" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					引用的模板,引用模板的ID
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="filename" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>
					生成的文件名称.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="extName" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>
					文件扩展名 如: .htm
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="dir" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					生成的文件存放的目录.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="genMode" type="GenModel" use="required">
			<xs:annotation>
				<xs:documentation>
					产生一个文件/产生多个文件
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
	<xs:simpleType name="GenModel">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MultiFile">
				<xs:annotation>
					<xs:documentation>产生多个文件,这个时候需要填写扩展名属性</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="SingleFile">
				<xs:annotation>
					<xs:documentation>产生一个文件,这个时候需要填写文件名称</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== 001466/codegen/build/codegenconfigext.xml
<?xml version="1.0" encoding="gbk" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="codegen.xsd">
	<charset>UTF-8</charset>
	<!--
	<database dbHelperClass="com.codash.cgm.db.impl.MySqlHelper" url="jdbc:mysql://localhost:3306/bgb?useUnicode=true&amp;characterEncoding=utf-8" username="root" password="root"/>
	<database dbHelperClass="com.codash.cgm.db.impl.MySqlHelper" url="jdbc:mysql://localhost:3306/bpm?useUnicode=true&amp;characterEncoding=utf-8" username="root" password="000"/>
	-->
	<database dbHelperClass="com.codash.cgm.db.impl.Sql2005Helper" url="jdbc:sqlserver://192.168.1.33;databaseName=DBIS" username="sa" password="bgb"/>

	<variables>
		<variable name="developer" value="codash" />
		<variable name="email" value="240018840@qq.com" />
		<variable name="company" value="gbg" />
	</variables>
	
	<templates basepath="D:\DBIS\DBIS\metadata\codegen\templateext">
		<template id="javaMapper" path="javaMapper.ftl" />
		<template id="javaModel" path="javaModel.ftl" />
		<template id="javaDao" path="javaDao.ftl" />
		<template id="javaController" path="javaController.ftl" />
		<template id="javaFormcontroller" path="javaFormcontroller.ftl"/>
		<template id="javaService" path="javaService.ftl" />
		<template id="javaFormValid" path="javaFormValid.ftl" />
		<template id="javaFormproperties_zh_CN" path="javaFormproperties_zh_CN.ftl" />
		<template id="javaFormproperties_en" path="javaFormproperties_en.ftl" />

		<template id="jsSearchForm" path="jsSearchForm.js"/>
		<template id="jsUpdateWin" path="jsUpdateWin.js"/>
		<template id="jsSearchGrid" path="jsSearchGrid.js"/>
		<template id="jsView" path="jsView.js"/>
		<template id="jsController" path="jsController.js" />
		<template id="jsModel" path="jsModel.js" />
		<template id="jsStore" path="jsStore.js" />
	</templates>
	
	<files baseDir="D:\DBIS\DBIS" >
		<file refTemplate="javaModel" filename="{class}.java" dir="src\main\java\com\codash\platform\model" />
		<file refTemplate="javaDao" filename="{class}Dao.java" dir="src\main\java\com\codash\platform\dao\{package}" />
		<file refTemplate="javaService" filename="{class}Service.java" dir="src\main\java\com\codash\platform\service\{package}" />
		<file refTemplate="javaController" filename="{class}Controller.java" dir="src\main\java\com\codash\platform\controller\{package}" />
		<file refTemplate="javaFormcontroller" filename="{class}FormController.java" dir="src\main\java\com\codash\platform\controller\{package}" />
		<file refTemplate="javaMapper" filename="{class}.map.xml" dir="src\main\resources\com\codash\platform\maper" />
		<file refTemplate="javaFormValid" filename="formValid.xml" dir="src\main\resources\conf\valid" append="true" insertTag="&lt;/formset&gt;" startTag="&lt;!--start_{tabname}--&gt;" endTag="&lt;!--end_{tabname}--&gt;"/>
		<file refTemplate="javaFormproperties_zh_CN" filename="form_zh_CN.properties" dir="src\main\resources\resource" append="true" insertTag="#insertbefore" startTag="#start_{tabname}" endTag="#end_{tabname}" />
		<file refTemplate="javaFormproperties_en" filename="form_en.properties" dir="src\main\resources\resource" append="true" insertTag="#insertbefore" startTag="#start_{tabname}" endTag="#end_{tabname}" />

		<file refTemplate="jsSearchForm" filename="SearchForm.js" dir="src\main\webapp\app\view\{jsPackage}" />
		<file refTemplate="jsUpdateWin" filename="UpdateWin.js" dir="src\main\webapp\app\view\{jsPackage}" />	
		<file refTemplate="jsSearchGrid" filename="SearchGrid.js" dir="src\main\webapp\app\view\{jsPackage}" />	
		<file refTemplate="jsView" filename="{class}.js" dir="src\main\webapp\app\view\{jsPackage}" />	
		<file refTemplate="jsController" filename="{class}.js" dir="src\main\webapp\app\controller" />	
		<file refTemplate="jsModel" filename="{class}Model.js" dir="src\main\webapp\app\model" />	
		<file refTemplate="jsStore" filename="{class}Store.js" dir="src\main\webapp\app\store" />	
	</files>
	
	<table tableName="Company" >
		<variable name="class"      value="Company" />
		<variable name="classVar"   value="company" />
		<variable name="package"    value="exchange" /><!--java package-->
		<variable name="path"       value="exchange" /> <!--path must as the same package-->
		<variable name="jsPackage"  value="company" />
	</table>
	
	
	
	<!-- 
	<genAll tableNames="CMS_COLUMN,CMS_LINK,TB_CMS_CREATE_TABLE">
		<file refTemplate="allTable" dir="E:\temp\cms\all" filename="alltable.html"  genMode="SingleFile"></file>
		<file refTemplate="tbdoc" dir="E:\temp\cms\all" extName="html"  genMode="MultiFile"></file>
	</genAll>
	 -->
</config>

=== 001466/codegen/bin/codegenconfigext.xml
<?xml version="1.0" encoding="gbk" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="codegen.xsd">
	<charset>UTF-8</charset>
	<!--
	<database dbHelperClass="com.codash.cgm.db.impl.MySqlHelper" url="jdbc:mysql://localhost:3306/bgb?useUnicode=true&amp;characterEncoding=utf-8" username="root" password="root"/>
	<database dbHelperClass="com.codash.cgm.db.impl.MySqlHelper" url="jdbc:mysql://localhost:3306/bpm?useUnicode=true&amp;characterEncoding=utf-8" username="root" password="000"/>
	-->
	<database dbHelperClass="com.codash.cgm.db.impl.Sql2005Helper" url="jdbc:sqlserver://192.168.1.33;databaseName=dic" username="sa" password="bgb"/>

	<variables>
		<variable name="developer" value="codash" />
		<variable name="email" value="240018840@qq.com" />
		<variable name="company" value="gbg" />
	</variables>
	
	<templates basepath="D:\fatest\dbi\metadata\codegen\templateext">
		<template id="javaMapper" path="javaMapper.ftl" />
		<template id="javaModel" path="javaModel.ftl" />
		<template id="javaDao" path="javaDao.ftl" />
		<template id="javaController" path="javaController.ftl" />
		<template id="javaFormcontroller" path="javaFormcontroller.ftl"/>
		<template id="javaService" path="javaService.ftl" />
		<template id="javaFormValid" path="javaFormValid.ftl" />
		<template id="javaFormproperties_zh_CN" path="javaFormproperties_zh_CN.ftl" />
		<template id="javaFormproperties_en" path="javaFormproperties_en.ftl" />

		<template id="jsSearchForm" path="jsSearchForm.js"/>
		<template id="jsUpdateWin" path="jsUpdateWin.js"/>
		<template id="jsSearchGrid" path="jsSearchGrid.js"/>
		<template id="jsView" path="jsView.js"/>
		<template id="jsController" path="jsController.js" />
		<template id="jsModel" path="jsModel.js" />
		<template id="jsStore" path="jsStore.js" />
	</templates>
	
	<files baseDir="D:\fatest\dbi" >
				
				
				
				
		<file refTemplate="javaModel" filename="{class}.java" 					dir="src\main\java\com\codash\platform\{package}\model" />
		<file refTemplate="javaMapper" filename="{class}.map.xml" 				dir="src\main\java\com\codash\platform\{package}\model" />

		<file refTemplate="javaDao" filename="{class}Dao.java" 					dir="src\main\java\com\codash\platform\{package}\dao" />
		<file refTemplate="javaService" filename="{class}Service.java" 			dir="src\main\java\com\codash\platform\{package}\service" />
		
		<file refTemplate="javaController" filename="{class}Controller.java" 			dir="src\main\java\com\codash\platform\{package}\controller" />
		<file refTemplate="javaFormcontroller" filename="{class}FormController.java" 	dir="src\main\java\com\codash\platform\{package}\controller" />
	
	
		<file refTemplate="javaFormValid" filename="{class}.valid.xml" 						dir="src\main\java\com\codash\platform\{package}\model"/>
		<file refTemplate="javaFormproperties_zh_CN" filename="{class}_zh_CN.properties" 	dir="src\main\java\com\codash\platform\{package}\model"/>
		<file refTemplate="javaFormproperties_en" filename="{class}_en.properties" 			dir="src\main\java\com\codash\platform\{package}\model"/>
		
		
		<file refTemplate="jsModel" filename="{class}Model.js" 					dir="src\main\java\com\codash\platform\{package}\web\model" />	
		<file refTemplate="jsStore" filename="{class}Store.js" 					dir="src\main\java\com\codash\platform\{package}\web\store" />
		<file refTemplate="jsSearchForm" filename="{class}SearchForm.js" 		dir="src\main\java\com\codash\platform\{package}\web\view" />
		<file refTemplate="jsUpdateWin" filename="{class}UpdateWin.js" 			dir="src\main\java\com\codash\platform\{package}\web\view" />	
		<file refTemplate="jsSearchGrid" filename="{class}SearchGrid.js" 		dir="src\main\java\com\codash\platform\{package}\web\view" />	
		<file refTemplate="jsView" filename="{class}View.js" 					dir="src\main\java\com\codash\platform\{package}\web\view" />	
		<file refTemplate="jsController" filename="{class}Controller.js" 		dir="src\main\java\com\codash\platform\{package}\web\controller" />	
		
		
		
		
		
	</files>
	
	
	
	<table tableName="SYS_TYPE_CLASS" >
		<variable name="class"      value="SysTypeClass" />
		<variable name="classVar"   value="sysTypeClass" />
		<variable name="jsPackage"  value="sysdic" />
		<variable name="package"    value="sysdic" />
		<variable name="path"       value="sysdic" /> 
	</table>
	
	
	
	<!-- 
	
	
	
	
	
	<table tableName="SYS_AUDIT" >
		<variable name="class"      value="SysAudit" />
		<variable name="classVar"   value="sysAudit" />
		<variable name="jsPackage"  value="sysaudit" />
		<variable name="package"    value="sysaudit" />
		<variable name="path"       value="sysaudit" /> 
	</table>
	
	<table tableName="SYS_USER_ROLE" >
		<variable name="class"      value="SysUserRole" />
		<variable name="classVar"   value="sysUserRole" />
		<variable name="jsPackage"  value="sysrole" />
		<variable name="package"    value="sysrole" />
		<variable name="path"       value="sysrole" /> 
	</table>
	
	
	<table tableName="SYS_ROLE" >
		<variable name="class"      value="SysRole" />
		<variable name="classVar"   value="sysRole" />
		<variable name="jsPackage"  value="sysrole" />
		<variable name="package"    value="sysrole" />
		<variable name="path"       value="sysrole" /> 
	</table>
	
	
	<table tableName="SYS_ROLE_RES" >
		<variable name="class"      value="SysRoleResources" />
		<variable name="classVar"   value="sysRoleResources" />
		<variable name="jsPackage"  value="sysrole" />
		<variable name="package"    value="sysrole" />
		<variable name="path"       value="sysrole" /> 
	</table>
	
	
	
	
	
	
	
	<table tableName="SYS_DEPENDENCY" >
		<variable name="class"      value="SysDependency" />
		<variable name="classVar"   value="sysDependency" />
		<variable name="jsPackage"  value="sysresources" />
		<variable name="package"    value="sysresources" />
		<variable name="path"       value="sysresources" /> 
	</table>
	
	
	
	
	
	<table tableName="SYS_RES" >
		<variable name="class"      value="SysResources" />
		<variable name="classVar"   value="sysResources" />
		<variable name="jsPackage"  value="sysresources" />
		<variable name="package"    value="sysresources" />
		<variable name="path"       value="sysresources" /> 
	</table>
	
	
	
	 <table tableName="SYS_RESURL" >
		<variable name="class"      value="SysResourcesUrl" />
		<variable name="classVar"   value="sysResourcesUrl" />
		<variable name="jsPackage"  value="sysresources" />
		<variable name="package"    value="sysresources" />
		<variable name="path"       value="sysresources" /> 
	</table>
	
	 
 
	
	  
	
	<genAll tableNames="CMS_COLUMN,CMS_LINK,TB_CMS_CREATE_TABLE">
		<file refTemplate="allTable" dir="E:\temp\cms\all" filename="alltable.html"  genMode="SingleFile"></file>
		<file refTemplate="tbdoc" dir="E:\temp\cms\all" extName="html"  genMode="MultiFile"></file>
	</genAll>
	 -->
</config>
